name: Install minikube

on: [push]

jobs:
  example:
    name: Create a minikube-cluster for e2e testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.1.0
        with:
          minikube version: 'v1.11.0'
          kubernetes version: 'v1.17.7'
      - name: Interact with the cluster
        run: kubectl get nodes
